SET ( libs_path $ENV{LIBRARY_PATH})
get_filename_component(env_scripts_path ${CMAKE_CURRENT_LIST_FILE} DIRECTORY)
file(GLOB env_scripts "${env_scripts_path}/env_*.cmake")
if (env_scripts)
  foreach(env_script ${env_scripts})
    include(${env_script})
  foreach()
endif()
unset(libs_path)
unset(env_script)
unset(env_scripts_path)
